apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: RolePolicyAttachment
metadata:
  name: sample-cluster-policy
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleRef:
      name: sample-eks-cluster
---
apiVersion: iam.aws.jet.crossplane.io/v1alpha1
kind: RolePolicyAttachment
metadata:
  name: sample-vpc-resource-controller
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
    roleRef:
      name: sample-eks-cluster