apiVersion: iam.aws.tf.crossplane.io/v1alpha1
kind: UserPolicy
metadata:
  name: sample-user-policy
spec:
  forProvider:
    region: ""
    userRef:
      name: sample-user
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
