apiVersion: neptune.aws.jet.crossplane.io/v1alpha2
kind: ClusterInstance
metadata:
  name: sample-instance
spec:
  forProvider:
    region: eu-central-1
    applyImmediately: true
    clusterIdentifierRef:
      name: sample-cluster
    engine: neptune
    instanceClass: db.r4.large
