apiVersion: rds.aws.jet.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: sample-cluster
spec:
  forProvider:
    region: us-west-1
    engine: aurora-postgresql
    masterUsername: cpadmin
    masterPasswordSecretRef:
      name: sample-cluster-password
      namespace: crossplane-system
      key: password
    skipFinalSnapshot: true
  writeConnectionSecretToRef:
    name: sample-rds-cluster-secret
    namespace: crossplane-system