apiVersion: rds.aws.jet.crossplane.io/v1alpha1
kind: DBParameterGroup
metadata:
  name: example-dbparametergroup
spec:
  forProvider:
    region: us-east-1
    family: postgres12
    description: example
    parameter:
      - name: application_name
        value: "example"
        applyMethod: immediate