apiVersion: rds.aws.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example-dbinstance
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    instanceClass: db.t2.micro
    name: example
    engine: postgres
    engineVersion: "12.4"
    username: adminuser
    passwordSecretRef:
      key: password
      name: example-dbinstance
      namespace: crossplane-system
    backupWindow: "09:46-10:16"
    maintenanceWindow: "Mon:00:00-Mon:03:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    parameterGroupNameRef:
      name: example-dbparametergroup
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance
  namespace: crossplane-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123