---
apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-jet-provider-account-b
spec:
  assumeRoleARN: "arn:aws:iam::999999999999:role/account_b"
  credentials:
    source: Secret
    secretRef:
      name: example-aws-jet-creds
      namespace: crossplane-system
      key: credentials
