apiVersion: ecrpublic.aws.jet.crossplane.io/v1alpha2
kind: Repository
metadata:
  name: sample-repository
spec:
  forProvider:
    region: us-east-1
    catalogData:
      - aboutText: Created with Crossplane
        description: A sample public repository
        operatingSystems:
          - Linux