apiVersion: ec2.aws.tf.crossplane.io/v1alpha1
kind: EC2NetworkInterface
metadata:
  name: sample-ni
spec:
  forProvider:
    region: us-west-1
    subnetIdRef:
      name: sample-subnet1
    privateIps:
      - "10.0.10.100"
