apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: NetworkInterface
metadata:
  name: sample-ni
spec:
  forProvider:
    region: us-west-1
    subnetIdRef:
      name: sample-subnet1
    privateIps:
      - "172.16.10.100"
