apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: Cluster
metadata:
  name: sample-cluster
spec:
  forProvider:
    region: us-west-1
    engine: memcached
    nodeType: cache.t2.micro
    numCacheNodes: 1
    parameterGroupName: default.memcached1.6
    port: 11211